# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-07 19:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181007_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to=settings.AUTH_USER_MODEL),
        ),
    ]
